In [1]:
# Import necessary libraries
from sklearn.datasets import load_digits
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score, confusion_matrix
from scipy.stats import mode
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Load the digits dataset
digits = load_digits()
X = digits.data # Feature vectors
y = digits.target # True labels
# Initialize the K-Means model with 10 clusters (one for each digit)
kmeans = KMeans(n_clusters=10, random_state=42)
kmeans.fit(X)
# Predict the cluster labels
cluster_labels = kmeans.labels_
label_mapping = np.zeros_like(cluster_labels)
for i in range(10):
    mask= (cluster_labels == i)
    label_mapping[mask] = mode(y[mask])[0]
# Calculate the accuracy
accuracy = accuracy_score(y, label_mapping)
print(f"K-Means Clustering Accuracy: {accuracy * 100:.2f}%")
# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y, label_mapping))





K-Means Clustering Accuracy: 86.14%

Confusion Matrix:
[[176   0   0   0   2   0   0   0   0   0]
 [  0 130  23   1   0   1   2   0   3  22]
 [  1   6 146  12   0   0   0   2   9   1]
 [  0   0   1 159   0   2   0   7   6   8]
 [  0  13   0   0 159   0   0   5   4   0]
 [  0   0   0   0   2 137   2   0   0  41]
 [  1   3   0   0   0   0 176   0   1   0]
 [  0   0   0   0   0   0   0 169  10   0]
 [  0  14   3   0   0   2   1   2 136  16]
 [  0   1   0   1   3   4   0   8   3 160]]
